window.challenges = {
  "version": "1.4ζ",
  "challenges": [
    ["Name generator", "credentials"],
    ["Higher/lower, heads/tails"],
    ["Temperature converter"],
    ["Calculate age in seconds", "with leap years"],
    ["Encryption/decryption algorithm"],
    ["Fizzbuzz"],
    ["Rock, paper, scissors", "lizard, Spock"],
    ["Project Euler", "in every language you know"],
    ["Hangman"],
    ["Love calculator"],
    ["Random sentence generator"],
    ["Password/passphrase generator"],
    ["Internet time", "(S)NTP"],
    ["Haiku generator"],
    ["Magic eight ball"],
    ["Collatz conjecture"],
    ["Reverse a string"],
    ["Eulerian path"],
    ["Simple file explorer"],
    ["Count words in a string", "lines, sentences, paragraphs, typos, &c."],
    ["Minesweeper"],
    ["Connect Four"],
    ["BMI calculator"],
    ["4chan thread/image downloader"],
    ["Sudoku generator/solver"],
    ["Maze generator/solver", "random graphs/trees"],
    ["Radix (base) converter"],
    ["Picross solver"],
    ["Fibonacci sequence"],
    ["Factorial"],
    ["Cipher encryption/decryption tool", 1],
    ["Blackjack"],
    ["Dungeons & Dragons with AI"],
    ["Generate ASCII tree"],
    ["Genetic algorithms on polygons"],
    ["Benford's law"],
    ["Currency converter", "various units, commodities, etc.", "history"],
    ["Static website generator"],
    ["Crossword game"],
    ["Scientific calculator", "GUI"],
    ["Perlin noise"],
    ["Image viewer"],
    ["ASCII digital clock"],
    ["Dijkstra's algorithm"],
    ["Text/Morse code translator", "with sound"],
    ["Tic-tac-toe"],
    ["Snake game"],
    ["FTP client", "server"],
    ["Telnet server", "client", "netcat clone"],
    ["IMP interpreter"],
    ["Tetris"],
    ["Conway's Game of Life", "other cell, automata"],
    ["Web crawler"],
    ["Text editor"],
    ["RSS feed reader"],
    ["RPN calculator"],
    ["Mandelbrot set", "other fractals"],
    ["Sorting algorithms", "visualization"],
    ["Custom markup → HTML converter"],
    ["N queens problem"],
    ["Flow in a network", "Ford-Fullerson algorithm"],
    ["Credential validator", "phone, email, &c.", 2],
    ["Linked list", "single and double"],
    ["Mastermind"],
    ["Random image generator", "parametric"],
    ["Ulam spiral"],
    ["Klingon translator", "bidirectional"],
    ["Prime number generator using a sieve"],
    ["Markov chains", "random text generation"],
    ["Graphical analog clock"],
    ["Two languages communicating with each other (C++/Java, Lisp/Python, &c.)", "without using the filesystem", "without using TCP"],
    ["Triangle number calculator"],
    ["Typing speed calculator"],
    ["Name art in ASCII"],
    ["Towers of Hanoi", "more disks, more poles"],
    ["Quine"],
    ["IRC bot"],
    ["Brainfuck interpreter", "optimization, multiple targets"],
    ["Knight's tour"],
    ["Chip-8 emulator"],
    ["Geek Code generator (v3.12)"],
    ["Define, translate, and rotate a polygon", "other affine transformations"],
    ["Pong with variable vectors"],
    ["Battleships with AI"],
    ["Simple paint program"],
    ["TCP chat with simple encryption"],
    ["Incremental economy simulator (à la 'Time of Exploration')"],
    ["Steganography (concealing data in other data)"],
    ["Pascal's triangle"],
    ["Sine wave generator from pseudorandom numbers"],
    ["Flappy Bird"],
    ["Fourier transform", "fast or 'slow' + visualization"],
    ["Method ringing simulator"],
    ["Binary search", "n-ary"],
    ["Nintendo Oil Panic"],
    ["Sierpinski triangle"],
    ["Dot & cross product of two vectors", "exterior product"],
    ["Little Man Computer emulator"],
    ["Lisp interpreter", "generic FFI for host language"],
    ["Enigma simulator with a configuration file", "decrypt messages without known settings"]
  ],
  "notes": {
    1: "Implement at least one of Rumkin Collection: http://rumkin.com/tools/cipher",
    2: "NB: http://www.mjt/me/uk/posts/falsehoods-programmers-believe-about-addresses/"
  }
};
